//! Tunable constants for the immersive-sim prototype. Kept in one place, as
//! in 009-derby, so the feel (map path, player size, sensitivity, ...) can
//! be iterated on without hunting through the systems that use them.

use bevy::prelude::*;

// --- Map -------------------------------------------------------------------

/// Which map to load, relative to `assets/`. `warehouse_bsp_source.map`
/// compiles to `warehouse.bsp` via `make bsp`; swap this to that `.bsp` path
/// to demo baked lighting (the loader code doesn't change, `bevy_trenchbroom`
/// treats both as a `SceneRoot` source). Both are generated by
/// `tools/gen_map.py`.
pub const MAP_PATH: &str = "maps/immersive/warehouse.map";

// --- TrenchBroom -------------------------------------------------------------------

/// The TrenchBroom game name this example registers itself as — shows up in
/// TrenchBroom's "New Map" dialog.
pub const TB_GAME_NAME: &str = "bevy_game_bits_immersive";

/// TrenchBroom units per Bevy meter. 39.37008 is bevy_trenchbroom's own
/// default (1 unit = 1 inch); named here so it's visible next to the other
/// tuning constants rather than an unlabeled default buried in a builder.
pub const TB_SCALE: f32 = 39.37008;

/// `StandardMaterial::lightmap_exposure` override for BSP-baked lightmaps.
/// Bevy's own default makes lightmaps invisible (see the bevy_trenchbroom
/// manual's BSP Tips section) — unused until Phase 5, harmless before then
/// since it only touches materials loaded from a `.bsp`.
pub const LIGHTMAP_EXPOSURE: f32 = 10_000.0;

// --- Player ------------------------------------------------------------------

/// Player collider dimensions, in meters. `bevy_ahoy`'s kinematic controller
/// "behaves best" with a cylinder per its own docs.
pub const PLAYER_RADIUS: f32 = 0.4;
pub const PLAYER_HEIGHT: f32 = 1.8;

/// Mouse-look sensitivity: degrees of yaw/pitch per pixel of mouse motion.
pub const MOUSE_SENSITIVITY: f32 = 0.07;

/// The player's `avian3d` `Mass`, in kg — but read the caveat. `bevy_ahoy`
/// requires `RigidBody::Kinematic` on the character, and avian's solver
/// **ignores a kinematic body's mass entirely**. The *only* thing that reads
/// this number is `bevy_ahoy`'s `dynamics::apply_forces`, which shoves every
/// dynamic body the player touches with `impulse = mass * approach_speed`. So
/// in this example the constant is purely "how hard I can push a crate", not a
/// weight — a literal 70 here would launch a 25 kg crate at ~2.8x walking
/// speed and make a stack impossible to walk past. Set *below* the per-step
/// friction impulse of a resting crate so walking into the pile can't budge
/// it at all (the crates carry their real mass, `CRATE_MASS`, and high
/// friction). You grab crates, you don't shove them. See SPEC.md Phase 8.
pub const PLAYER_PUSH_MASS: f32 = 0.5;

// --- Crates (carryable props) ----------------------------------------------
//
// Metal crates the player grabs with RMB and stacks to reach platform B (deck
// top 4.88 m). The map pre-places one big ~800 kg crate (1.6 m, too heavy to
// lift) against the deck's south edge; the player hops onto it and stacks two
// loose 0.8 m crates on top (1.6 + 0.8 + 0.8 = 3.2 m, + a 1.8 m jump clears the
// deck). `PropCrate::size` / `mass` are per-entity; these are the defaults.
// See SPEC.md Phase 8.

/// Default edge length (meters) of a crate cube.
pub const CRATE_SIZE: f32 = 0.8;

/// Default crate `Mass` (kg). A level author overrides it per-entity via the
/// `mass` field to make one crate too heavy to lift (a fixed step).
pub const CRATE_MASS: f32 = 25.0;

/// Friction coefficient for crates — high, and applied with a `Max` combine
/// rule (`carry::spawn_crates`) so the crate-vs-floor friction is this value
/// regardless of the floor brush's own. Keeps a stack from sliding apart and
/// keeps the pile put when the player walks through it.
pub const CRATE_FRICTION: f32 = 0.95;

/// Linear/angular damping bled off a crate every step, so a bump becomes a
/// short lurch that settles instead of a long glide or spin.
pub const CRATE_LINEAR_DAMPING: f32 = 0.6;
pub const CRATE_ANGULAR_DAMPING: f32 = 1.5;

/// Crate look. The room is lit by one `DirectionalLight` + flat ambient and
/// has **no** environment map, so a physically-correct `metallic: 1.0` crate
/// renders nearly black (nothing for it to reflect). A low metallic with a
/// mid roughness reads as painted sheet metal and actually catches the light.
pub const CRATE_COLOR: Color = Color::srgb(0.42, 0.45, 0.5);
pub const CRATE_METALLIC: f32 = 0.25;
pub const CRATE_ROUGHNESS: f32 = 0.4;

// --- Carrying -------------------------------------------------------------

/// Heaviest `Mass` (kg) RMB will lift. Between `CRATE_MASS` and the "too
/// heavy" crates so the weight gate is demonstrable. Static brushes (ladders,
/// walls) and kinematic bodies (doors) are excluded by body *type* before
/// mass is ever consulted.
pub const CARRY_MAX_MASS: f32 = 40.0;

/// How far (meters) in front of the camera a held crate floats, and how far
/// below the view centre. Also the max distance the drop/throw shape-cast
/// probes for clear space.
pub const CARRY_DISTANCE: f32 = 1.25;
pub const CARRY_DROP: f32 = 0.4;

/// Alpha a held crate is drawn at (ghost preview).
pub const CARRY_ALPHA: f32 = 0.5;

/// Seconds of held RMB for a fully-charged throw.
pub const CARRY_CHARGE_SECS: f32 = 1.5;

/// RMB held shorter than this counts as a *place* (drop straight down, no
/// launch speed) rather than a weak throw — so stacking is precise.
pub const CARRY_PLACE_SECS: f32 = 0.2;

/// Launch speed (m/s) of a fully-charged throw; scaled by the charge ratio.
pub const CARRY_THROW_SPEED: f32 = 12.0;

// --- Lighting ------------------------------------------------------------

/// Illuminance (lux) of the directional light. See `main.rs::spawn_light` for
/// why a directional light is used instead of the map's `light` entity. The
/// warehouse is much bigger and its dev textures much darker than the Phase 1
/// room, so this and `AMBIENT_BRIGHTNESS` are both well up from the old 3000.
pub const SUN_ILLUMINANCE: f32 = 10_000.0;

/// Flat fill light so the warehouse floor and undersides of the platforms
/// aren't pitch black. Bevy's default ambient is far too weak for a room
/// this size.
pub const AMBIENT_BRIGHTNESS: f32 = 800.0;

// --- Interaction -----------------------------------------------------------

/// How far (meters) the "use" raycast reaches from the camera.
pub const INTERACT_RANGE: f32 = 2.5;

// --- Ladder climbing -------------------------------------------------------
//
// Half-Life-style: aim at a ladder and press E to lock on, forward climbs and
// backward descends, mouse-look stays free, E or Space lets go. `ladder.rs`
// brackets bevy_ahoy's controller rather than hooking into it. See SPEC.md
// Phase 7.

/// Vertical climb speed in meters/second when holding full forward/back.
/// Deliberately slow — a ladder is not a lift.
pub const LADDER_CLIMB_SPEED: f32 = 2.2;

/// How hard the body is pulled onto the ladder's centre line (exponential
/// `smooth_nudge` decay rate). The body overlaps the ladder's sensor volume
/// HL-style, so there's no standoff — just this pull toward the middle.
/// High enough to feel stuck, not so high it snaps visibly on grab.
pub const LADDER_SNAP_RATE: f32 = 16.0;

/// How far (meters) in front of the ladder's centre line the climber's body —
/// and so the camera — sits while locked on. The body hangs on the ladder's
/// front face rather than inside it, which is both what a climber does and the
/// only way the rungs are visible: the visual is `LADDER_VISUAL_DEPTH` deep, so
/// at 0 you are looking through it. Must clear
/// `LADDER_VISUAL_DEPTH / 2 + PLAYER_RADIUS` — a hard requirement now that the
/// visual carries a solid collider: any less and the mount snap would spawn
/// the body inside the rungs and avian would shove it back out. The surplus
/// over that minimum is framing.
pub const LADDER_STANDOFF: f32 = 0.7;

/// Exponential decay rate for the yaw ease that turns the view to face the
/// rungs after an E-grab (`1 - e^(-rate·dt)` per frame). ~24 settles in about
/// 0.15 s. Same units as `LADDER_SNAP_RATE`; pitch is never touched.
pub const LADDER_TURN_RATE: f32 = 24.0;

/// Upward speed (m/s) given when jumping off a ladder.
pub const LADDER_JUMP_OFF: f32 = 4.0;

/// Speed (m/s) away from the ladder face when jumping off, so the hop clears
/// the rungs instead of sliding back on.
pub const LADDER_PUSH_OFF: f32 = 3.5;

/// How far (meters) `climb` walks the body forward off the top of a ladder,
/// measured from the ladder's own centre line, before it detaches and hands
/// back to the controller (`Climbing::crest`). Has to clear the ladder's
/// half-depth, the `LADDER_STANDOFF` the body hangs at, the body radius and a
/// margin, so you let go well inside the deck rather than on its lip — the
/// deliberate "haul yourself over the top" lurch.
pub const LADDER_DISMOUNT_STEP: f32 = 1.6;

// --- Ladder visual -------------------------------------------------------------
//
// The `func_ladder` brush is a `skip`-textured invisible volume; `ladder.rs`
// builds this low-poly rails-and-rungs mesh in its place, sized from the
// volume's width/height. Swap for a glTF `SceneRoot` later — it's one mesh.

/// Square cross-section (meters) of each vertical rail.
pub const LADDER_RAIL_THICKNESS: f32 = 0.05;

/// Square cross-section (meters) of each rung.
pub const LADDER_RUNG_THICKNESS: f32 = 0.04;

/// Meters between rung centres up the ladder.
pub const LADDER_RUNG_SPACING: f32 = 0.30;

/// Front-to-back depth (meters) of the visual *and its solid collider*. The
/// sensor grab volume is far deeper, but invisible and non-blocking — this is
/// how chunky the rails/rungs look and how far out the player is stopped.
pub const LADDER_VISUAL_DEPTH: f32 = 0.10;

/// Base color of the temporary grey ladder material.
pub const LADDER_COLOR: Color = Color::srgb(0.55, 0.55, 0.58);

// --- Pickups -----------------------------------------------------------------

/// Edge length (meters) of the placeholder pickup cube.
pub const PICKUP_SIZE: f32 = 0.3;
pub const PICKUP_COLOR: Color = Color::srgb(1.0, 0.8, 0.15);
pub const PICKUP_EMISSIVE: LinearRgba = LinearRgba::rgb(1.5, 1.0, 0.1);

// --- Devtools ------------------------------------------------------------

/// A leg of the `IMMERSIVE_AUTOPILOT` script: hold this movement input, turn
/// at this yaw rate (degrees/sec), hold the real `Space` key down for the
/// whole leg if `jump` (so consecutive `jump` legs are one continuous hold),
/// and — if `interact` — tap the real E key for `AUTOPILOT_TAP_SECS` (starting
/// the frame something focuses) — all for `duration` seconds. See `devtools.rs`
/// for why this is the way this example can verify live movement on a machine
/// where synthetic keyboard/mouse input is blocked.
pub struct AutopilotStep {
    pub duration: f32,
    pub movement: bevy::math::Vec2,
    pub yaw_rate: f32,
    pub interact: bool,
    pub jump: bool,
    /// Hold the real RMB (`MouseButton::Right`) down for the whole leg, like
    /// `jump` holds `Space` — so a leg's `duration` *is* the throw-charge
    /// time. A run of `grab` legs is one continuous hold.
    pub grab: bool,
    /// Absolute camera pitch (degrees, negative = look down) held for the leg.
    /// The crate script needs this: a crate is 0.8 m tall and sits on the
    /// floor, so an eye-level ray sails over it — you look down to aim at one.
    /// The ladder script leaves it 0.
    pub pitch_deg: f32,
}

/// How long (seconds) the autopilot holds a tapped `E` "use" press. Long enough
/// to span many frames — a one-frame tap would fire once whether or not the
/// action is edge-triggered, and so would prove nothing — and short enough to
/// release before the leg ends, so the next leg's press is a fresh edge for a
/// `Press` condition to fire on. (`Space` isn't tapped — it's held for the
/// whole of a `jump` leg.)
pub const AUTOPILOT_TAP_SECS: f32 = 0.15;

/// The keyboard-free ladder check. In order: walk straight into the rungs with
/// no E press — `climbing` must stay false (no on-contact grab) and `x` must
/// stall at ~-0.67 against the visual's solid collider (without it the body
/// walks clean through, under deck A, to the west wall at x ~-11); then a short
/// approach pressing E (mounts only when the "use" ray focuses the ladder,
/// never on contact) — grab #1, with no
/// jump held, the baseline; press E again to toggle off and drop to the floor
/// at the mount; settle; then **jump straight up** from the mount and, still
/// holding Space, press E in the air — grab #2, with Space pressed well before
/// the grab and still down as it lands. Grab #2 is the regression: pre-fix,
/// `stash_input`'s age-checked `jumped` read fed that live (elapsed-0) buffer
/// to `climb`'s jump branch the frame after the grab and knocked you straight
/// off — a coin flip on E's exact timing, so the climb often needed a *second*
/// E press. With the fix `let_go_on_jump` keys on the `Start<Jump>` press edge,
/// which was raised before `Climbing` ever existed, so grab #2 holds and rides
/// to the top. From there the climb is split FWD / STILL / FWD: climb partway,
/// **let go** (the STILL leg's `y` must stay flat with `climbing` still true —
/// the stop-when-released check; pre-fix the last wish sticks and `y` climbs on
/// regardless), then resume and the top-of-range rule steps the body onto
/// platform A (`grounded`, `y` ~5.8). Pre-fix the detached body instead walks
/// forward through the sensor and on to the far wall (`x` ~-11, `y` ~0.9),
/// platform never reached — the binary regression signal.
/// Each interact leg is one `AUTOPILOT_TAP_SECS` E press starting the frame the
/// raycast first catches the ladder; a run of `jump` legs is one continuous
/// `Space` hold. With `Interact` edge-triggered (`Press`) the sequence is
/// deterministic. The yaw ease's *feel*, the top-of-deck E-grab and a *fresh*
/// jump-off mid-climb are left for a person.
const FWD: bevy::math::Vec2 = bevy::math::Vec2::new(0.0, 1.0);
const STILL: bevy::math::Vec2 = bevy::math::Vec2::ZERO;

pub const AUTOPILOT_SCRIPT: &[AutopilotStep] = &[
    // Walk into the ladder, no E press. Two proofs in one leg: `climbing` stays
    // false while the body is pressed against the rungs (no on-contact grab),
    // and `x` stalls at ~-0.67 — the visual's solid collider. Without that
    // collider the body walks straight through, under deck A, to the west wall
    // at x ~-11, y ~0.9 (the binary regression signal).
    AutopilotStep {
        duration: 3.0,
        movement: FWD,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: 0.0,
    },
    // Grab #1 — already parked in front of the rungs with `focus` resolved, so
    // one E press on this leg's first frame mounts. `climbing` must be false
    // every sample before it (the proof the on-contact grab is gone) and steady
    // true after (not flap — the proof `Interact` is edge-triggered). No prior
    // jump, so the buffer is clean.
    AutopilotStep {
        duration: 1.0,
        movement: STILL,
        yaw_rate: 0.0,
        interact: true,
        jump: false,
        grab: false,
        pitch_deg: 0.0,
    },
    // Press E on the rungs: toggle off. `climbing` -> false, gravity drops the
    // body...
    AutopilotStep {
        duration: 1.2,
        movement: STILL,
        yaw_rate: 0.0,
        interact: true,
        jump: false,
        grab: false,
        pitch_deg: 0.0,
    },
    // ...straight down to the floor (`grounded` true, `y` ~0.9) at the mount —
    // the camera is still facing the rungs, so no re-approach is needed.
    AutopilotStep {
        duration: 1.6,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: 0.0,
    },
    // Jump straight up from the mount: press Space (the `Start<Jump>` edge) and
    // hold it. STILL, so the body rises and falls on the spot, staying in the
    // ladder's interact range the whole arc.
    AutopilotStep {
        duration: 0.35,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: true,
        grab: false,
        pitch_deg: 0.0,
    },
    // Grab #2 — still airborne, Space still held (so `jumped` is live,
    // elapsed-0). One E tap, fired the frame the raycast focuses the ladder.
    // With the fix `let_go_on_jump` keys on the `Start<Jump>` *edge* — raised a
    // leg ago, before `Climbing` existed — so nothing detaches: `climbing` goes
    // true and holds. Pre-fix `stash_input`'s age-checked `jumped` read passes
    // that live stopwatch straight to `climbing.jump` -> `climb` detaches on the
    // next step and the body drops back to the mount.
    AutopilotStep {
        duration: 2.5,
        movement: STILL,
        yaw_rate: 0.0,
        interact: true,
        jump: true,
        grab: false,
        pitch_deg: 0.0,
    },
    // Climb partway (Space released now). From the grab-#2 height (`y` ~1.4) at
    // ~2.2 m/s this reaches `y` ~4 — well short of the ladder top (`y` ~6.18).
    AutopilotStep {
        duration: 1.2,
        movement: FWD,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: 0.0,
    },
    // Let go mid-climb. The stop-when-released check: `y` must be *constant*
    // across every telemetry sample of this leg with `climbing` still true.
    // Pre-fix `stash_input` keeps the last non-zero wish, so `y` keeps rising,
    // tops out and crests onto platform A during this leg instead.
    AutopilotStep {
        duration: 1.5,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: 0.0,
    },
    // Resume: the climb restarts from where it hung, reaches the top and the
    // top-of-range rule steps onto platform A (`grounded`, `y` ~5.8). Pre-fix
    // the detached body is already on the far wall by now (`y` ~0.9).
    AutopilotStep {
        duration: 3.0,
        movement: FWD,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: 0.0,
    },
    // Hold on the platform.
    AutopilotStep {
        duration: 3.0,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: 0.0,
    },
];

/// The keyboard-free crate check, selected by `IMMERSIVE_AUTOPILOT=crates`.
/// The map puts a normal crate and a deliberately over-mass crate on the line
/// *behind* the spawn (clear of the ladder walk); the script turns 180° first,
/// then drives with pure forward/back movement (no yaw). It *does* pitch the
/// view down — a floor crate is below an eye-level ray — via
/// `AutopilotStep::pitch_deg`. `grab` holds the real RMB for the whole leg
/// (like `jump` holds Space), so a `grab` leg's `duration` is the throw charge
/// and a run of `grab` legs is one press.
///
/// `crates(n=)` in telemetry counts only *liftable* crates (mass <=
/// `CARRY_MAX_MASS`) — 4 at rest here: the autopilot's normal crate + the 3
/// stacking crates by platform B. The heavy crates (400 kg, 800 kg) don't
/// count.
///
/// Legs and their binary signals (read from `IMMERSIVE_TELEMETRY`):
///  1. walk into the crate, no RMB — `crates(moving)` stays 0 and its position
///     barely changes: `PLAYER_PUSH_MASS` is below a resting crate's friction
///     impulse, so the pile doesn't budge.
///  2-3. RMB on the (now focused) crate — `carrying` goes true (n -> 3) and
///     *stays* true across the release (`release_prop` no-ops without a
///     `ThrowCharge`).
///  4-5. RMB down and HELD past `CARRY_CHARGE_SECS` (`charge` climbs, caps at
///     1.5), then release — a full throw: n back to 4, `crates(moving)` -> 1,
///     the crate arcs several metres.
///  6-9. walk to where it landed, RMB grab, RMB tap (< `CARRY_PLACE_SECS`) —
///     a place: `carrying` -> false, the crate drops straight down and settles.
///
/// The weight gate (RMB on the 400 kg crate leaves `carrying` false) and the
/// ladder reject share the one `matches!(.. RigidBody::Dynamic .. mass <=
/// CARRY_MAX_MASS)` in `start_grab_or_charge`; both are left to the human pass
/// (the immovable crate blocks the autopilot's aisle, and a crate placed at
/// your feet sits in the look-down ray's blind spot until you step back — a
/// real quirk, not a bug).
//
// NB `movement` legs are *short*: bevy_ahoy walks at 12 m/s and the crates sit
// ~1-3 m apart, so 0.5 s is already a full traverse. The throw comes first,
// off the guaranteed-fresh first grab.
pub const AUTOPILOT_SCRIPT_CRATES: &[AutopilotStep] = &[
    // 0. Turn 180 deg to face the crates (they sit behind the spawn, away from
    //    the ladder walk). `yaw_rate` is deg/sec, summed by `autopilot_look`.
    AutopilotStep {
        duration: 1.0,
        movement: STILL,
        yaw_rate: 180.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: -20.0,
    },
    // 1. Walk into the normal crate, looking down at it. Push-mass check:
    //    `focus` catches "Hold crate", `moving` stays 0, the crate stays put.
    AutopilotStep {
        duration: 0.9,
        movement: FWD,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: -45.0,
    },
    // 2-3. Grab (RMB press then release). `carrying` -> true (n 3), stays true
    //    past the release.
    AutopilotStep {
        duration: 0.5,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: true,
        pitch_deg: -45.0,
    },
    AutopilotStep {
        duration: 0.5,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: -18.0,
    },
    // 4-5. Arm + fully charge a throw (RMB held past `CARRY_CHARGE_SECS`), then
    //    release: a hard throw. `charge` climbs to 1.5, then n -> 4,
    //    `moving` -> 1, the crate arcs several metres.
    AutopilotStep {
        duration: 2.0,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: true,
        pitch_deg: -12.0,
    },
    AutopilotStep {
        duration: 1.4,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: -12.0,
    },
    // 6-7. Walk to where the thrown crate landed and settle on it (no RMB) so
    //    `focus` locks on.
    AutopilotStep {
        duration: 0.7,
        movement: FWD,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: -40.0,
    },
    AutopilotStep {
        duration: 0.8,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: -45.0,
    },
    // 8-9. Grab it (press/release), then TAP RMB (< `CARRY_PLACE_SECS`): a
    //    place. `carrying` briefly true then false; the crate drops straight
    //    down and settles (`moving` -> 0).
    AutopilotStep {
        duration: 0.6,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: true,
        pitch_deg: -45.0,
    },
    AutopilotStep {
        duration: 0.5,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: -18.0,
    },
    AutopilotStep {
        duration: 0.15,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: true,
        pitch_deg: -18.0,
    },
    AutopilotStep {
        duration: 2.5,
        movement: STILL,
        yaw_rate: 0.0,
        interact: false,
        jump: false,
        grab: false,
        pitch_deg: -18.0,
    },
];

/// How often (seconds) `IMMERSIVE_TELEMETRY` logs player state.
pub const TELEMETRY_INTERVAL: f32 = 0.25;
